export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const CHANGE_USER_PASSWORD = 'CHANGE_USER_PASSWORD';
export const CHANGE_USER_DATA = 'CHANGE_USER_DATA';
export const BIND_EMAIL = 'BIND_EMAIL';
export const ADMIN_RESET_USER_PASSWORD = 'ADMIN_RESET_USER_PASSWORD';
