export const SIGN_IN = 'SIGN_IN';
export const FETCH_LOGGED_USER = 'FETCH_LOGGED_USER';
export const SIGN_OUT = 'SIGN_OUT';
export const REGISTER_USER = 'REGISTER_USER';
export const VERIFIED_EMAIL = 'VERIFIED_EMAIL';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const CHANGE_EMAIL = 'CHANGE_EMAIL';
export const TOGGLE_CURRENT_USER_EMAIL_NOTIFICATION =
  'TOGGLE_CURRENT_USER_EMAIL_NOTIFICATION';
export const SIGN_IN_BY_PROVIDER = 'SIGN_IN_BY_PROVIDER';
export const PROVIDER_CALLBACK = 'PROVIDER_CALLBACK';
