export const GET_FINANCE_OPERATIONS = 'GET_FINANCE_OPERATIONS';
export const GET_ALL_FINANCE_OPERATIONS = 'GET_ALL_FINANCE_OPERATIONS';
export const GET_FINANCE_OPERATION = 'GET_FINANCE_OPERATION';
export const ADD_FINANCE_OPERATION = 'ADD_FINANCE_OPERATION';
export const CHANGE_STATUS_FINANCE_OPERATION =
  'CHANGE_STATUS_FINANCE_OPERATION';
export const CHANGE_STATUS_FINANCE_OPERATION_TO_CANCEL =
  'CHANGE_STATUS_FINANCE_OPERATION_TO_CANCEL';
