export const SET_FINANCE_OPERATIONS = 'SET_FINANCE_OPERATIONS';
export const SET_FINANCE_OPERATION = 'SET_FINANCE_OPERATION';
export const ADD_FINANCE_OPERATION = 'ADD_FINANCE_OPERATION';
export const CHANGE_STATUS_FINANCE_OPERATION =
  'CHANGE_STATUS_FINANCE_OPERATION';
