export const GET_USER_WALLETS_BY_WALLET_TYPE_ID =
  'GET_USER_WALLETS_BY_WALLET_TYPE_ID';
export const GET_USER_WALLETS = 'GET_USER_WALLETS';
export const ADD_USER_WALLET = 'ADD_USER_WALLET';
export const UPDATE_USER_WALLET = 'UPDATE_USER_WALLET';
export const DELETE_USER_WALLET = 'DELETE_USER_WALLET';
