export const SET_USER_WALLETS_BY_WALLET_TYPE_ID =
  'SET_USER_WALLETS_BY_WALLET_TYPE_ID';
export const SET_USER_WALLETS = 'SET_USER_WALLETS';
export const ADD_USER_WALLET = 'ADD_USER_WALLET';
export const UPDATE_USER_WALLET = 'UPDATE_USER_WALLET';
export const DELETE_USER_WALLET = 'DELETE_USER_WALLET';
