export const SEND_SUPPORT_REQUEST = 'SEND_SUPPORT_REQUEST';
export const SEND_SUPPORT_REQUEST_MESSAGE = 'SEND_SUPPORT_REQUEST_MESSAGE';
export const GET_SUPPORT_REQUESTS = 'GET_SUPPORT_REQUESTS';
export const GET_SUPPORT_REQUEST_MESSAGES = 'GET_SUPPORT_REQUEST_MESSAGES';
export const GET_SUPPORT_REQUEST = 'GET_SUPPORT_REQUEST';
export const SET_SUPPORT_REQUEST_STATUS = 'SET_SUPPORT_REQUEST_STATUS';
export const GET_SUPPORT_REQUESTS_BY_CRITERIA =
  'GET_SUPPORT_REQUESTS_BY_CRITERIA';
