export const SET_SUPPORT_REQUESTS = 'SET_SUPPORT_REQUESTS';
export const SET_SUPPORT_REQUEST_MESSAGES = 'SET_SUPPORT_REQUEST_MESSAGES';
export const SET_SUPPORT_REQUEST = 'SET_SUPPORT_REQUEST';
export const ADD_SUPPORT_REQUEST_MESSAGE = 'ADD_SUPPORT_REQUEST_MESSAGE';
export const UPDATE_SUPPORT_REQUEST = 'UPDATE_SUPPORT_REQUEST';
