export const GET_CURRENT_CATEGORY = 'GET_CURRENT_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_WITH_PRODUCTS_FOR_USER =
  'GET_CATEGORIES_WITH_PRODUCTS_FOR_USER';
