export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_CATEGORIES_WITH_PRODUCTS_FOR_USER =
  'SET_CATEGORIES_WITH_PRODUCTS_FOR_USER';
